compact_course/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'compact_course.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('web_app.urls')),
    url(r'^ap-courses/submit$', include('web_app.urls')),
    url(r'^(?P<course_type_slug>[-\w]+)$', include('web_app.urls')),
    url(r'^ap-courses/(?P<course_slug>[-\w]+)/(?P<chapter_slug>[-\w]+)/lesson$', include('web_app.urls')),
    url(r'^ap-courses/(?P<course_slug>[-\w]+)/(?P<chapter_slug>[-\w]+)/compact-review$', include('web_app.urls')),
    url(r'^ap-courses/(?P<course_slug>[-\w]+)/(?P<chapter_slug>[-\w]+)/problems$', include('web_app.urls')),)

web_app/urls.py
from django.conf.urls import patterns, url
from web_app import views

urlpatterns = patterns('',
                       url(r'^$', views.splash, name='splash'),
                       url(r'^ap-courses/submit$', views.submit, name="submit"),
                       url(r'^(?P<course_type_slug>[-\w]+)$', views.courses_page, name='courses'),
                       url(r'^ap-courses/(?P<course_slug>[-\w]+)$', views.chapter_page, name="chapter"),
                       url(r'^ap-courses/(?P<course_slug>[-\w]+)/(?P<chapter_slug>[-\w]+)/lesson$', views.chapter, name="lesson"),
                       url(r'^ap-courses/(?P<course_slug>[-\w]+)/(?P<chapter_slug>[-\w]+)/compact-review$', views.chapter, name="review"),
                       url(r'^ap-courses/(?P<course_slug>[-\w]+)/(?P<chapter_slug>[-\w]+)/problems$', views.chapter, name="problems"),)

web_app/models.py
from django.db import models
from django import forms


class Problem(models.Model):
    question = models.TextField()


class Choice(models.Model):
    problem = models.ForeignKey(Problem)
    choice_text = models.TextField()
    correct_choice = models.BooleanField()


class Quiz(models.Model):
    title = models.TextField()
    problems = models.ManyToManyField(Problem)


class Section(models.Model):
    '''
    e.g. Motion Definitions, Graphic Relationships, etc.
    '''

    title = models.TextField()
    content = models.TextField()
    subsections = models.ManyToManyField('self')

    def __unicode__(self):
        return "{0}, {1}".format(self.title, self.content)


class Lesson(models.Model):
    sections = models.ManyToManyField(Section)

    def __unicode__(self):
        return "{0}".format(self.sections.all())


class CompactReview(models.Model):
    sections = models.ManyToManyField(Section)

    def __unicode__(self):
        return "{0}".format(self.sections.all())


class Chapter(models.Model):
    '''
    e.g. Vectors, Kinematics, etc.
    '''

    title = models.TextField()
    preview = models.TextField()
    slug = models.TextField()
    image = models.ImageField(blank=True, null=True, upload_to='./chapter_images/', default='./chapter_images/chapter_image.png')

    compact_review = models.OneToOneField(CompactReview, null=True, blank=True)
    lesson = models.OneToOneField(Lesson, null=True, blank=True)
    quiz = models.OneToOneField(Quiz, null=True, blank=True)

    def __unicode__(self):
        return "{0}, {1}".format(self.title, self.preview)


class Subject(models.Model):
    '''
    e.g. AP Physics B, etc.
    '''

    title = models.TextField()
    preview = models.TextField()
    slug = models.TextField()
    image = models.ImageField(blank=True, null=True, upload_to='./subject_images/', default='./subject_images/subject_image.png')

    chapters = models.ManyToManyField(Chapter)

    def __unicode__(self):
        return "{0}, {1}".format(self.title, self.preview)


class SubjectType(models.Model):
    '''
    e.g. Math, science, etc.
    '''

    title = models.TextField()
    subjects = models.ManyToManyField(Subject)


    def get_all_subjects(self):
        return sorted(self.subjects.all(), key=lambda subject: subject.title)

    def __unicode__(self):
        return "{0}, {1}".format(self.title, self.subjects.all())


class CourseType(models.Model):
    '''
    e.g. AP Courses, College Courses, etc.
    '''

    title = models.TextField()
    slug = models.TextField()
    subject_types = models.ManyToManyField(SubjectType)

    def __unicode__(self):
        return "{0}, {1}".format(self.title, self.subject_types.all())


class ChapterForm(forms.Form):
    subject = forms.CharField()
    chapter = forms.CharField()
    section = forms.CharField()
    content = forms.CharField()
    subsection = forms.CharField()
    sub_content = forms.CharField()

web_app/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.utils.text import slugify
from web_app.models import *


def splash(request):
    return render_to_response('web_app/splash.html')


def courses_page(request, course_type_slug):
    course_type = CourseType.objects.filter(slug=course_type_slug)[0]
    subject_types = [course_type.subject_types.get(title="Math"),
                     course_type.subject_types.get(title="Science"),
                     course_type.subject_types.get(title="Social Studies"),
                     course_type.subject_types.get(title="Language")]

    return render_to_response('web_app/base_listing.html',
                              {'course_type': course_type,
                               'subject_types': subject_types},
                              RequestContext(request))


def chapter_page(request, course_slug):
    subject = Subject.objects.get(slug=course_slug)
    subject_types = SubjectType.objects.all()

    subject_type = [_ for _ in subject_types if subject in _.subjects.all()][0]
    course_type = [_ for _ in CourseType.objects.all() if subject_type in _.subject_types.all()][0]

    chapters = subject.chapters.all()

    return render_to_response('web_app/course_page.html',
                              {'subject_types': subject_types,
                               'course_type': course_type,
                               'subject_type': subject_type,
                               'subject': subject,
                               'chapters': chapters},
                              RequestContext(request))


def chapter(request, course_slug, chapter_slug):
    subject = Subject.objects.get(slug=course_slug)
    subject_types = SubjectType.objects.all()

    subject_type = [_ for _ in subject_types if subject in _.subjects.all()][0]
    course_type = [_ for _ in CourseType.objects.all() if subject_type in _.subject_types.all()][0]

    chapters = subject.chapters.all()
    chapter = subject.chapters.get(slug=chapter_slug)

    path = request.get_full_path().split('/')[-1]
    if path == 'lesson':
        sections = chapter.lesson.sections.all()
    elif path == 'compact-review':
        sections = chapter.compact_review.sections.all()
    elif path == 'problems':
        pass
        # sections = chapter.lesson.sections.all()

    return render_to_response('web_app/chapter.html',
                              {'chapter_type': path,
                               'subject_types': subject_types,
                               'course_type': course_type,
                               'subject_type': subject_type,
                               'subject': subject,
                               'chapters': chapters,
                               'chapter': chapter,
                               'sections': sections},
                              RequestContext(request))


def submit(request):
    if request.method == "POST":
        form = ChapterForm(request.POST)

        form.is_valid()

        try:
            subsection = form.cleaned_data['subsection']
            sub_content = form.cleaned_data['sub_content']
            sub = True
        except Exception as e:
            sub = False

        try:
            subject = form.cleaned_data['subject']
            subject_object = Subject.objects.get(slug=slugify(unicode(subject)))

            chapter = form.cleaned_data['chapter']
            chapter_object = subject_object.chapters.get(slug=slugify(unicode(chapter)))

            section = form.cleaned_data['section']
            section_object = chapter_object.lesson.sections.get(title=section)

            content = form.cleaned_data['content']
            section_object.content = content

            if sub:
                try:
                    subsection_object = section_object.subsections.get(title=subsection)
                    subsection_object.content = sub_content
                    subsection_object.save()
                except Exception as e:
                    return render_to_response('web_app/submit.html',
                                              {'success': False,
                                               'error': str(e)},
                                              RequestContext(request))

            section_object.save()
            return render_to_response('web_app/submit.html',
                                      {'success': True,
                                       'error': "POSTED"},
                                      RequestContext(request))

        except Exception as e:
            return render_to_response('web_app/submit.html',
                                      {'success': False,
                                       'error': str(e)},
                                      RequestContext(request))


    elif request.method == "GET":
        return render_to_response('web_app/submit.html',
                                  {'success': True,
                                   'error': None},
                                  RequestContext(request))

# def chapter_quiz(request, course_slug, chapter_slug):

templates/web_app/base_listing.html
<!DOCTYPE html>
<html lang="en">
  {% load static bootstrap3 %}
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />

    <!-- Lobster font -->
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lobster"></link>

    <!-- Font Awesome -->
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

    <!-- jQuery -->
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.js"></script>

    <!-- Bootstrap -->
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}

    <!-- Organic -->
    <link rel="stylesheet" href="{% static 'css/listing.css' %}"></link>
    <link rel="stylesheet" href="{% static 'css/all.css' %}"></link>
    <script type="text/javascript" src="{% static 'js/listing.js' %}"></script>
  </head>
  <body>
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle Navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="display:inline !important;">CompactCourse</a>
    </div>
      <div style="float:right; color:white; margin-top:15px;"><i class="fa fa-search fa-lg"></i></div>
  </div>
</div>

    <div id='{{ subject.slug }}' class="bs-header" style="background:url({% static 'media/ap-courses.png' %}) no-repeat center center fixed; background-size:cover;">
      <div class="container">
        <h1>{{ course_type.title }}</h1>
      </div>
    </div>


    <div class="container">
        <div class="col-md-12">
          <div class="panel-group" id="accordion">
            {% for subject_type in subject_types %}
              <div class="panel panel-info outer">
                <div class="panel-heading outer">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse-{{ subject_type.id }}">
                  <h3>{{ subject_type.title }} &nbsp; <small>The study of {{ subject_type.title|lower }}</small></h3><i class="fa fa-level-down"></i>
                </a>
                </div>
                <div class="panel-collapse collapse" id="collapse-{{ subject_type.id }}" style="height: auto;">
                  <div class="panel-body">
                    <div class="panel-group" id="accordion-inner">

                      {% for subject in subject_type.get_all_subjects %}
                      <div class="panel panel-default" id="{{ subject.title }}-panel">
                        <div class="panel-heading">
                          <h4 class="panel-title" onClick="activate('#{{ subject.slug }}-panel')"><a href="#{{ subject.slug }}-collapse" data-toggle="collapse" data-parent="#accordion-inner">{{ subject.title|slice:"3:" }}</a><i class="fa fa-external-link"></i></h4>
                        </div>

                        <div class="panel-collapse collapse" id="{{ subject.slug }}-collapse">
                          <div class="panel-body">
                            <ul class="list-group">
                        {% for chapter in subject.chapters.all %}
                              <a href="./ap-courses/{{ subject.slug }}/{{ chapter.slug }}/lesson" id="{{ subject.slug }}-{{ chapter.slug }}" class="list-group-item">
                                <h4 class="list-group-item-heading">{{ chapter.title }}</h4>
                                {# <p class="list-group-item-text">{{ chapter.preview }}</p> #}
                              </a>
                        {% endfor %}
                            </ul>

                          </div>
                        </div>

                      </div>
                      {% endfor %}

                    </div>
                  </div>
                </div>
              </div>
              <br>
            {% endfor %}
          </div>
        </div>
      </div>
      <br>
      <br>
    </div>
  </body>
</html>

templates/web_app/chapter.html
<!DOCTYPE html>
<html lang="en">
{% load static bootstrap3 %}

<head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />

    <!-- Lobster font -->
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lobster"></link>

    <!-- jQuery -->
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.js"></script>

    <!-- Bootstrap -->
    {% bootstrap_css %}
    {% bootstrap_messages %}

    <!-- Organic -->
    <link rel="stylesheet" href="{% static 'css/chapter.css' %}"></link>
    <link rel="stylesheet" href="{% static 'css/all.css' %}"></link>
    <style>
    .bs-header {
      background: url({{ STATIC_URL }}media/{{ subject.title|slugify }}.png) no-repeat center center fixed;
      background-size: cover;
    }
    </style>

    <title>{{ subject.title }} &middot {{ chapter.title }}</title>
</head>

{% autoescape off %}
<body>
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle Navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">CompactCourse</a>
    </div>
    <div class="navbar-collapse collapse" style="margin-right:10px;">
      <ul class="nav navbar-nav">
        <li id="nav-active" class="active"><a href="../../{{ subject.slug }}">{{ subject.title }}</a></li>

        {% for subject_type in subject_types %}
        <li class="dropdown" id="{{ subject_type.title|slugify }}">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            {{ subject_type.title }}<b class="caret"></b>
          </a>

              <ul class="dropdown-menu">
              {% for subject in subject_type.subjects.all %}
                <li><a href="../../{{ subject.slug }}">{{ subject.title }}</a></li>
              {% endfor %}
              </ul>
        </li>
        {% endfor %}

      </ul>
    </div>
  </div>
</div>

<div class="bs-header">
  <h1>{{ chapter.title }}</h1>
  <br>
  <br>

  {% if chapter_type == 'lesson' %}
    <div class="btn-group">
        <button class="btn btn-md active" href="#">
          Lesson
        </button>
    </div>
    <div class="btn-group">
        <button class="btn btn-md" onclick="window.location.href='./compact-review'" style="font-family:'Lobster',cursive;">CompactReview</button>
    </div>
    <div class="btn-group">
        <button class="btn btn-md" onclick="window.location.href='./problems'">Problems</button>
    </div>
  {% elif chapter_type == 'compact-review' %}
    <div class="btn-group">
        <button class="btn btn-md" onclick="window.location.href='./lesson'">
          Lesson
        </button>
    </div>
    <div class="btn-group">
        <button class="btn btn-md active" style="font-family:'Lobster',cursive;">CompactReview</button>
    </div>
    <div class="btn-group">
        <button class="btn btn-md" onclick="window.location.href='./problems'">Problems</button>
    </div>
  {% elif chapter_type == 'problems' %}
    <div class="btn-group">
        <button class="btn btn-md" onclick="window.location.href='./lesson'">
          Lesson
        </button>
    </div>
    <div class="btn-group">
        <button class="btn btn-md" onclick="window.location.href='./compact-review'" style="font-family:'Lobster',cursive;">CompactReview</button>
    </div>
    <div class="btn-group">
        <button class="btn btn-md active" href="#">Problems</button>
    </div>
  {% endif %}

</div>

{% if chapter_type == 'lesson' %}
<div class="col-md-3">
<div class="bs-docs-sidebar hidden-print" role="complementary">
    <ul class="nav bs-docs-sidenav">
        <li style="font-family:'Lobster',cursive;">
            <a id="show-button" href="#" style="font-size:12pt;">
                Show Chapters
            </a>
        </li>
        <hr style="margin-top:8px; margin-bottom:8px;"/>

        {% for chapter in chapters %}
        <li class="chapter" style="display:none;"><a href="../{{ chapter.title|slugify }}/lesson">
            {{ chapter.title }}
        </a></li>
        {% endfor %}

        {% for section in sections %}
        <li class="section"><a href="#{{ section.title|slugify }}">
            {{ section.title }}
          </a>
            {% if section.subsections.all %}
               <ul class="nav">
                {% for subsection in section.subsections.all %}
                  <li class="section">
                    <a href="#{{ subsection.title|slugify }}">
                      {{ subsection.title }}
                    </a>
                  </li>
                {% endfor %}
               </ul>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
</div>
</div>

<div class="col-md-9" role="main">
    {% for section in sections %}
        <h2 id="{{ section.title|slugify }}">{{ section.title }}</h2>
        <hr>
        {% autoescape off %}
        <p>{{ section.content }}</p>
            {% if section.subsections.all %}
                {% for subsection in section.subsections.all %}
                    <h3 id="{{ subsection.title|slugify }}">
                      {{ subsection.title }}
                    </h3>
                    <hr>
                    <p>{{ subsection.content }}</p>
                {% endfor %}
            {% endif %}

        {% endautoescape %}
    {% endfor %}
</div>
{% elif chapter_type == 'compact-review' %}

<link rel="stylesheet" href="{% static 'css/compact_review.css' %}"></link>

<br>
<br>
<div class="col-md-12">
  <div class="panel-group" id="accordion">
    {% for section in sections %}
      <div class="panel panel-info">
        <div class="panel-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse-{{ section.id }}">
          <h3>{{ section.title }}</h3><i class="fa fa-level-down"></i>
        </a>
        </div>
        <div class="panel-collapse collapse" id="collapse-{{ section.id }}" style="height: auto;">
          <div class="panel-body">
          {% autoescape off %}
          {{ section.content }}
          {% endautoescape %}
          </div>
        </div>
      </div>
      <br>
    {% endfor %}
  </div>
</div>

{% endif %}

{% bootstrap_javascript %}
<script type="text/javascript" src="{% static 'js/docs.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/chapter_after.js' %}"></script>
</body>

{% endautoescape %}

</html>

templates/web_app/chapter_quiz.html
<!DOCTYPE html>
<html lang="en">
{% load static bootstrap3 %}

<head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />

    <!-- Lobster font -->
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lobster"></link>

    <!-- jQuery -->
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.js"></script>

    <!-- Bootstrap -->
    {% bootstrap_css %}
    {% bootstrap_messages %}

    <!-- Organic -->
    <link rel="stylesheet" href="{% static 'css/listing.css' %}"></link>
    <link rel="stylesheet" href="{% static 'css/chapter.css' %}"></link>
    <style>
    .bs-header {
      margin-top: -20px;
      margin-bottom: 20px;
      padding-top: 25px;
      padding-bottom: 25px;
      text-align: center;
      background: url({{ STATIC_URL }}/media/{{ subject.title|slugify }}.png) no-repeat center center fixed;
      background-size: cover;
      border-bottom: #ddd solid 1px;
    }

    .bs-header h1 {
      font-family: 'Lobster', cursive;
      font-size: 48px;
    }
    </style>

    <title>{{ subject.title }} &middot {{ chapter.title }}</title>
</head>

<body>
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle Navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">CompactCourse</a>
    </div>
    <div class="navbar-collapse collapse" style="margin-right:10px;">
      <form action="/search/" class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input class="form-control" placeholder="Search" type="text" name="q" value="">
        </div>
        <div class="form-group">
          <select class="form-control" name="type">
            <option value="">Everything</option>
          </select>
        </div>
        <input type="submit" class="btn btn-default" value="Go">
      </form>
      <ul class="nav navbar-nav">
        <li id="nav-active" class="active"><a href="../../../{{ course_type.title|slugify }}">{{ course_type.title }}</a></li>

        {% for subject_type in subject_types %}
        <li class="dropdown" id="{{ subject_type.title|slugify }}">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            {{ subject_type.title }}<b class="caret"></b>
          </a>

          {% for subject in subject_type.subjects.all %}
              <ul class="dropdown-menu">
                <li><a href="../../{{ subject.title|slugify }}">{{ subject.title }}</a></li>
              </ul>
          {% endfor %}
        </li>
        {% endfor %}

      </ul>
    </div>
  </div>
</div>

<div class="bs-header">
<h1>{{ subject.title }} &middot {{ chapter.title }}</h1>
</div>

<div class="container">

<ul class="nav nav-tabs nav-justified">
  {% if chapter_type == 'lesson' %}
    <li class="active">
        <a href="#">
          Lesson
        </a>
    </li>
    <li>
        <a href="./compact-review" style="font-family:'Lobster',cursive;">CompactReview
    </a></li>
    <li>
        <a href="./problems">Problems</a>
    </li>
  {% elif chapter_type == 'compact-review' %}
    <li>
        <a href="./lesson">
          Lesson
        </a>
    </li>
    <li class="active">
        <a href="#" style="font-family:'Lobster',cursive;">CompactReview
    </a></li>
    <li>
        <a href="./problems">Problems</a>
    </li>
  {% elif chapter_type == 'problems' %}
    <li>
        <a href="./lesson">
          Lesson
        </a>
    </li>
    <li>
        <a href="./compact-review" style="font-family:'Lobster',cursive;">CompactReview
    </a></li>
    <li class="active">
        <a href="#">Problems</a>
    </li>
  {% endif %}
</ul>

<div class="row">
<div class="col-md-3">
<div class="bs-docs-sidebar hidden-print" role="complementary">
    <ul class="nav bs-docs-sidenav">
        <li style="font-family:'Lobster',cursive;">
            <a id="show-button" href="#" style="font-size:12pt;">
                Show Chapters
            </a>
        </li>
        <hr style="margin-top:8px; margin-bottom:8px;"/>

        {% for chapter in chapters %}
        <li class="chapter" style="display:none;"><a href="../{{ chapter.title|slugify }}/lesson">
            {{ chapter.title }}
        </a></li>
        {% endfor %}

        {% for section in sections %}
        <li class="section"><a href="#{{ section.title|slugify }}">
            {{ section.title }}
          </a>
            {% if section.subsections.all %}
               <ul class="nav">
                {% for subsection in section.subsections.all %}
                  <li class="section">
                    <a href="#{{ subsection.title|slugify }}">
                      {{ subsection.title }}
                    </a>
                  </li>
                {% endfor %}
               </ul>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
</div>
</div>

<div class="col-md-9" role="main">
    {% for section in sections %}
        <h2 id="{{ section.title|slugify }}">{{ section.title }}</h2>
        <hr>
        {% autoescape off %}
        <p>{{ section.content }}</p>
            {% if section.subsections.all %}
                {% for subsection in section.subsections.all %}
                    <h3 id="{{ subsection.title|slugify }}">
                      {{ subsection.title }}
                    </h3>
                    <hr>
                    <p>{{ subsection.content }}</p>
                {% endfor %}
            {% endif %}

        {% endautoescape %}
    {% endfor %}
</div>
</div>
</div>

{% bootstrap_javascript %}
<script type="text/javascript" src="{% static 'js/docs.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/chapter_after.js' %}"></script>
</body>
</html>

templates/web_app/splash.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/splash.css' %}" />

<title>Compact &middot; Course</title>
</head>

<body>
<div class="container theme-showcase container-shifted" role="main">
    <div class="jumbotron jumbopaque" style="text-align:center;">
      <div class="logo"></div>
      <br />
      <br />
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
      <br />
      <p>
        <a href="/ap-courses" class="btn btn-default btn-lg btn-themed" role="button">AP Courses</a>
        <a href="#" class="btn btn-default btn-lg btn-themed" role="button">College Courses</a>
      </p>
      <p>
        <a href="#" class="btn btn-default btn-lg btn-themed" role="button">Subjects</a>
        <a href="#" class="btn btn-default btn-lg btn-themed" role="button">AP Calculator</a>
      </p>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script type="text/javascript" src="../static/js/bootstrap.min.js"></script>
</body>

</html>

templates/web_app/submit.html
<!DOCTYPE html>
<html lang="en">

{% load static bootstrap3 %}

<head>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />

  <!-- Lobster font -->
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lobster"></link>

  <!-- jQuery -->
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.js"></script>

  <!-- Bootstrap -->
  {% bootstrap_css %}
  {% bootstrap_messages %}

  <!-- Organic -->
  <link rel="stylesheet" href="{% static 'css/course_page.css' %}"></link>
  <link rel="stylesheet" href="{% static 'css/all.css' %}"></link>
</head>
<body>
  <div class="container">
    <br>
    <div class="alert alert-danger">All forms are case and white-space sensitive!
      Get exact names from the course pages.
      You can only edit existing <b>sections</b>.
    </div>

    {% if success and not error %}

      <form id="submit_form" action="/ap-courses/submit" method="post">
        {% csrf_token %}
        <p>
          <label for="subject">Subject (AP Physics B, etc.)</label><br>
          <input type="text" name="subject" id="id_subject" />
        </p>
        <p>
          <label for="chapter">Chapter (Vectors, etc.)</label><br>
          <input type="text" name="chapter" id="id_chapter" />
        </p>

        <br>
        <hr><p><b>Lesson</b></p><hr>
        <div>
          <p>
            <label for="section">Section (Vector Definitions, etc.)</label><br>
            <input type="text" name="section" id="id_section" />
            <br>
            <br>
            <label for="content">Section Content (raw HTML)</label><br>
            <textarea rows="20" cols="150" type="text" name="content" id="id_content"></textarea>
          </p>



        <div class="panel-group" id="accordion">
          <div class="panel panel-primary">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse-one">
                  Subsection (leave blank if none)
                </a>
              </h4>
            </div>
            <div class="panel-collapse collapse in" id="collapse-one" style="height: auto;">
              <div class="panel-body">
                <label for="subsection">Subsection (leave blank if none)</label><br>
                <input type="text" name="subsection" id="id_subsection" />
                <br>
                <br>
                <label for="sub_content">Subsection Content (raw HTML)</label><br>
                <textarea rows="20" cols="150" type="text" name="sub_content" id="id_sub_content"></textarea>
              </div>
            </div>
          </div>
        </div>
        </div>
        <input type="submit" value="Submit" />
      </form>

    {% elif success and error == "POSTED" %}

      <div class="alert alert-success">Success! <b>Hit back</b> to automatically fill in the form again.</div>

    {% else %}

      <div class="alert alert-error">Error! <b>{{ error }}</b></div>

    {% endif %}

  <br>
  </div>

{% bootstrap_javascript %}
<script type="text/javascript">$(".collapse").collapse()</script>
</body>
</html>